project_id = "pfmlfpatsxfkzfnytmec"

[functions.admin-bot]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.tg-support]
verify_jwt = false

[functions.tg-toggle-like]
verify_jwt = false

[functions.tg-toggle-favorite]
verify_jwt = false

[functions.tg-add-comment]
verify_jwt = false

[functions.tg-get-article-state]
verify_jwt = false

[functions.tg-report-article]
verify_jwt = false
